<?php 

namespace Jemer\Faker;

class Lists
{
    static $BlogCategories = [
        "Technology Trends",  
        "Personal Development",  
        "Health and Wellness",  
        "Travel and Adventure",  
        "Food and Recipes",  
        "Parenting and Family",  
        "Finance and Investing",  
        "Entrepreneurship",  
        "Digital Marketing",  
        "Photography Tips",  
        "Fitness and Exercise",  
        "Mental Health",  
        "Education and Learning",  
        "Sustainable Living",  
        "Home Improvement",  
        "Career Advice",  
        "Social Media Strategies",  
        "Fashion and Style",  
        "Beauty and Skincare",  
        "Gaming and Esports",  
        "Science and Research",  
        "Automotive",  
        "Real Estate",  
        "Book Reviews",  
        "Movies and TV Shows",  
        "Music and Entertainment",  
        "Art and Design",  
        "Writing and Blogging",  
        "Spirituality and Mindfulness",  
        "Wedding Planning",  
        "Gardening",  
        "DIY Projects",  
        "Pet Care",  
        "Event Planning",  
        "Tech Reviews",  
        "Cryptocurrency and Blockchain",  
        "Eco-Friendly Products",  
        "Self-Care Tips",  
        "Life Hacks",  
        "Productivity and Time Management",  
        "Startup Stories",  
        "Work-Life Balance",  
        "Sports and Athletics",  
        "Language Learning",  
        "Volunteering and Nonprofits",  
        "History and Culture",  
        "Luxury Lifestyle",  
        "Adventure Sports",  
        "Public Speaking",  
        "Leadership Skills",  
    ];

    static $MensNames = [
                            "James",  
                            "John",  
                            "Robert",  
                            "Michael",  
                            "William",  
                            "David",  
                            "Joseph",  
                            "Thomas",  
                            "Charles",  
                            "Christopher",  
                            "Daniel",  
                            "Matthew",  
                            "Anthony",  
                            "Mark",  
                            "Donald",  
                            "Paul",  
                            "Steven",  
                            "Andrew",  
                            "Kenneth",  
                            "George",  
                            "Joshua",  
                            "Kevin",  
                            "Brian",  
                            "Edward",  
                            "Ronald",  
                            "Timothy",  
                            "Jason",  
                            "Jeffrey",  
                            "Ryan",  
                            "Jacob",  
                            "Gary",  
                            "Nicholas",  
                            "Eric",  
                            "Jonathan",  
                            "Larry",  
                            "Frank",  
                            "Scott",  
                            "Justin",  
                            "Brandon",  
                            "Raymond",  
                            "Gregory",  
                            "Samuel",  
                            "Patrick",  
                            "Benjamin",  
                            "Jack",  
                            "Dennis",  
                            "Jerry",  
                            "Alexander",  
                            "Tyler",  
                            "Henry",  
                        ];


    static $WomensNames = [
                            "Mary",  
                            "Patricia",  
                            "Jennifer",  
                            "Linda",  
                            "Elizabeth",  
                            "Barbara",  
                            "Susan",  
                            "Jessica",  
                            "Sarah",  
                            "Karen",  
                            "Nancy",  
                            "Lisa",  
                            "Margaret",  
                            "Betty",  
                            "Sandra",  
                            "Ashley",  
                            "Dorothy",  
                            "Kimberly",  
                            "Emily",  
                            "Donna",  
                            "Michelle",  
                            "Carol",  
                            "Amanda",  
                            "Melissa",  
                            "Deborah",  
                            "Stephanie",  
                            "Rebecca",  
                            "Sharon",  
                            "Laura",  
                            "Cynthia",  
                            "Kathleen",  
                            "Amy",  
                            "Angela",  
                            "Shirley",  
                            "Anna",  
                            "Brenda",  
                            "Pamela",  
                            "Emma",  
                            "Nicole",  
                            "Helen",  
                            "Samantha",  
                            "Katherine",  
                            "Christine",  
                            "Debra",  
                            "Rachel",  
                            "Catherine",  
                            "Carolyn",  
                            "Janet",  
                            "Ruth",  
                            "Maria",  
                        ];                        


static $StreetNames = [
                        "Main Street",  
                        "Oak Avenue",  
                        "Pine Street",  
                        "Maple Drive",  
                        "Cedar Lane",  
                        "Elm Street",  
                        "Willow Road",  
                        "Birch Avenue",  
                        "Chestnut Street",  
                        "Spruce Drive",  
                        "Walnut Lane",  
                        "Hillcrest Road",  
                        "Park Avenue",  
                        "Ridge Street",  
                        "Highland Drive",  
                        "Meadow Lane",  
                        "Sunset Boulevard",  
                        "River Road",  
                        "Broadway",  
                        "Washington Street",  
                        "Lincoln Avenue",  
                        "Adams Street",  
                        "Jefferson Road",  
                        "Madison Avenue",  
                        "Franklin Street",  
                        "Jackson Lane",  
                        "Roosevelt Drive",  
                        "Hamilton Road",  
                        "Grant Street",  
                        "Kennedy Boulevard",  
                        "Monroe Avenue",  
                        "Harrison Street",  
                        "Cleveland Road",  
                        "Taylor Lane",  
                        "Wilson Avenue",  
                        "Howard Street",  
                        "Johnson Drive",  
                        "Church Street",  
                        "Lake Avenue",  
                        "Forest Lane",  
                        "Valley Road",  
                        "Spring Street",  
                        "North Avenue",  
                        "South Street",  
                        "East Drive",  
                        "West Lane",  
                        "Center Street",  
                        "College Avenue",  
                        "Liberty Road",  
                        "Market Street",  
                    ];

    static $CardinalDirection = [
                                    "North",  
                                    "South",  
                                    "East",  
                                    "West",  
                                    "Northeast",  
                                    "Northwest",  
                                    "Southeast",  
                                    "Southwest",  
                                ];


    static $Email = [
                        "example1@email.com",  
                        "test.user@email.com",  
                        "fake.address@email.com",  
                        "sample123@email.com",  
                        "hello.world@email.com",  
                        "user.name@email.com",  
                        "john.doe@email.com",  
                        "jane.doe@email.com",  
                        "placeholder@email.com",  
                        "demo.account@email.com",  
                        "temp.mailer@email.com",  
                        "no.reply@email.com",  
                        "random.email@email.com",  
                        "my.email@email.com",  
                        "your.name@email.com",  
                        "trial.user@email.com",  
                        "contact.me@email.com",  
                        "first.last@email.com",  
                        "email.test@email.com",  
                        "test.account@email.com",  
                        "fake.user@email.com",  
                        "made.up@email.com",  
                        "norealaddress@email.com",  
                        "practice.email@email.com",  
                        "test123@email.com",  
                        "demo.email@email.com",  
                        "mailbox@email.com",  
                        "temporary@email.com",  
                        "myaccount@email.com",  
                        "quick.email@email.com",  
                        "your.email@email.com",  
                        "trial.account@email.com",  
                        "sample.user@email.com",  
                        "placeholder123@email.com",  
                        "test.name@email.com",  
                        "dummy.email@email.com",  
                        "check.mailer@email.com",  
                        "email.user@email.com",  
                        "mockup@email.com",  
                        "practice123@email.com",  
                        "send.email@email.com",  
                        "trial.name@email.com",  
                        "user.mailbox@email.com",  
                        "email.fake@email.com",  
                        "account123@email.com",  
                        "mock.email@email.com",  
                        "your.account@email.com",  
                        "temp123@email.com",  
                        "check.email@email.com",  
                        "trial.mailer@email.com",  
                        "email.placeholder@email.com",  
                    ];

    static $Countries = [
                        "United States",  
                        "Canada",  
                        "Mexico",  
                        "Brazil",  
                        "Argentina",  
                        "United Kingdom",  
                        "Germany",  
                        "France",  
                        "Italy",  
                        "Spain",  
                        "Russia",  
                        "China",  
                        "Japan",  
                        "India",  
                        "Australia",  
                        "New Zealand",  
                        "South Africa",  
                        "Nigeria",  
                        "Egypt",  
                        "Kenya",  
                        "Turkey",  
                        "Saudi Arabia",  
                        "South Korea",  
                        "Indonesia",  
                        "Thailand",  
                        "Vietnam",  
                        "Philippines",  
                        "Malaysia",  
                        "Singapore",  
                        "Pakistan",  
                        "Bangladesh",  
                        "Iran",  
                        "Iraq",  
                        "Israel",  
                        "Ukraine",  
                        "Poland",  
                        "Sweden",  
                        "Norway",  
                        "Finland",  
                        "Denmark",  
                        "Netherlands",  
                        "Belgium",  
                        "Portugal",  
                        "Greece",  
                        "Switzerland",  
                        "Austria",  
                        "Hungary",  
                        "Czech Republic",  
                        "Slovakia",  
                        "Romania",  
                        "Bulgaria",  
                        ];


    static $CityNames = [
                        "New York",  
                        "Los Angeles",  
                        "Chicago",  
                        "Houston",  
                        "Phoenix",  
                        "Philadelphia",  
                        "San Antonio",  
                        "San Diego",  
                        "Dallas",  
                        "San Jose",  
                        "Austin",  
                        "Jacksonville",  
                        "Fort Worth",  
                        "Columbus",  
                        "San Francisco",  
                        "Charlotte",  
                        "Indianapolis",  
                        "Seattle",  
                        "Denver",  
                        "Washington",  
                        "Boston",  
                        "El Paso",  
                        "Nashville",  
                        "Detroit",  
                        "Oklahoma City",  
                        "Las Vegas",  
                        "Portland",  
                        "Memphis",  
                        "Louisville",  
                        "Baltimore",  
                        "Milwaukee",  
                        "Albuquerque",  
                        "Tucson",  
                        "Fresno",  
                        "Sacramento",  
                        "Kansas City",  
                        "Atlanta",  
                        "Miami",  
                        "Colorado Springs",  
                        "Raleigh",  
                        "Omaha",  
                        "Long Beach",  
                        "Virginia Beach",  
                        "Oakland",  
                        "Minneapolis",  
                        "Tampa",  
                        "Tulsa",  
                        "Arlington",  
                        "New Orleans",  
                        "Wichita",  
                        "Cleveland",  
                        ];

    static $US_States = [
                        "Alabama",  
                        "Alaska",  
                        "Arizona",  
                        "Arkansas",  
                        "California",  
                        "Colorado",  
                        "Connecticut",  
                        "Delaware",  
                        "Florida",  
                        "Georgia",  
                        "Hawaii",  
                        "Idaho",  
                        "Illinois",  
                        "Indiana",  
                        "Iowa",  
                        "Kansas",  
                        "Kentucky",  
                        "Louisiana",  
                        "Maine",  
                        "Maryland",  
                        "Massachusetts",  
                        "Michigan",  
                        "Minnesota",  
                        "Mississippi",  
                        "Missouri",  
                        "Montana",  
                        "Nebraska",  
                        "Nevada",  
                        "New Hampshire",  
                        "New Jersey",  
                        "New Mexico",  
                        "New York",  
                        "North Carolina",  
                        "North Dakota",  
                        "Ohio",  
                        "Oklahoma",  
                        "Oregon",  
                        "Pennsylvania",  
                        "Rhode Island",  
                        "South Carolina",  
                        "South Dakota",  
                        "Tennessee",  
                        "Texas",  
                        "Utah",  
                        "Vermont",  
                        "Virginia",  
                        "Washington",  
                        "West Virginia",  
                        "Wisconsin",  
                        "Wyoming",  
                        ];

    static $US_States_Abbreviated = [
                                    "AL",  
                                    "AK",  
                                    "AZ",  
                                    "AR",  
                                    "CA",  
                                    "CO",  
                                    "CT",  
                                    "DE",  
                                    "FL",  
                                    "GA",  
                                    "HI",  
                                    "ID",  
                                    "IL",  
                                    "IN",  
                                    "IA",  
                                    "KS",  
                                    "KY",  
                                    "LA",  
                                    "ME",  
                                    "MD",  
                                    "MA",  
                                    "MI",  
                                    "MN",  
                                    "MS",  
                                    "MO",  
                                    "MT",  
                                    "NE",  
                                    "NV",  
                                    "NH",  
                                    "NJ",  
                                    "NM",  
                                    "NY",  
                                    "NC",  
                                    "ND",  
                                    "OH",  
                                    "OK",  
                                    "OR",  
                                    "PA",  
                                    "RI",  
                                    "SC",  
                                    "SD",  
                                    "TN",  
                                    "TX",  
                                    "UT",  
                                    "VT",  
                                    "VA",  
                                    "WA",  
                                    "WV",  
                                    "WI",  
                                    "WY",  
                                    ];

    static $LastNames = [
                        "Smith",  
                        "Johnson",  
                        "Williams",  
                        "Jones",  
                        "Brown",  
                        "Davis",  
                        "Miller",  
                        "Wilson",  
                        "Moore",  
                        "Taylor",  
                        "Anderson",  
                        "Thomas",  
                        "Jackson",  
                        "White",  
                        "Harris",  
                        "Martin",  
                        "Thompson",  
                        "Garcia",  
                        "Martinez",  
                        "Roberts",  
                        "Clark",  
                        "Rodriguez",  
                        "Lewis",  
                        "Lee",  
                        "Walker",  
                        "Hall",  
                        "Allen",  
                        "Young",  
                        "Hernandez",  
                        "King",  
                        "Wright",  
                        "Lopez",  
                        "Scott",  
                        "Adams",  
                        "Baker",  
                        "Gonzalez",  
                        "Nelson",  
                        "Carter",  
                        "Mitchell",  
                        "Perez",  
                        "Robinson",  
                        "Evans",  
                        "Green",  
                        "Turner",  
                        "Collins",  
                        "Cook",  
                        "Howard",  
                        "King",  
                        "Ward",  
                        "Flores",  
                        "Rivera",  
                        "Cooper",  
                        ];                                    

    static $Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non enim lectus. Integer sagittis, odio eu malesuada auctor, lorem mi ultricies sapien, et vehicula nulla tortor et felis. Ut auctor risus et neque vehicula, vitae tempor sem fermentum. Fusce nec felis nunc. Nunc at nisi felis. Nam eget felis a purus lacinia scelerisque. Aenean varius lectus vel felis auctor, ac gravida enim tincidunt. Sed placerat, tortor vel ultricies sollicitudin, nulla sapien venenatis tortor, eget fringilla ante risus id metus. Fusce malesuada, nunc sed eleifend lobortis, erat arcu maximus ante, ac elementum turpis nisi at eros. Mauris id bibendum arcu, sit amet suscipit sapien. Etiam nec augue at ante tempor lacinia. Sed tempor eros in mi dictum, sit amet finibus tortor sollicitudin. Ut ut nunc sem. Vivamus congue dolor vitae eros lacinia, vel facilisis risus vehicula. In euismod consequat erat. Donec laoreet diam sit amet tortor volutpat, sed dignissim nulla volutpat. Nulla varius orci eget nisl scelerisque, nec auctor orci rutrum. Sed ultricies sem vitae orci rutrum ultricies. Nunc non felis dui. Nullam euismod vitae mauris nec pretium. Cras et elit neque. Nam gravida, odio id placerat feugiat, augue justo pretium eros, at luctus justo urna sed erat. Integer vitae magna et nunc finibus sollicitudin. Suspendisse vehicula felis vitae dui varius, eget bibendum felis posuere. Etiam sit amet maximus libero, a tempor tortor. Maecenas viverra consectetur felis, nec dictum neque auctor nec. Nulla posuere quam ut ex varius, vel congue nulla mollis. Duis aliquet tempor felis ac lacinia. Etiam malesuada lectus id leo hendrerit, sit amet lacinia mi dictum. "; 

                        
    static $Passwords = [
                        "XyZ!9vT@2",  
                        "qWErT123$",  
                        "pAsSw0rd!8",  
                        "AbCdEfG$7",  
                        "ZyX!4567",  
                        "tY!uP#89",  
                        "1M9pWgD",  
                        "jK#6LmVq",  
                        "4wErT!123",  
                        "QzX@7sT8",  
                        ];


    static $Titles = [
                        "10 Tips for Mastering Time Management",  
                        "How to Stay Motivated During Tough Times",  
                        "5 Easy Recipes for Busy Weeknights",  
                        "Exploring the Best Travel Destinations of 2024",  
                        "Top 7 Fitness Trends to Watch This Year",  
                        "The Ultimate Guide to Starting Your Own Business",  
                        "How to Build a Successful Personal Brand",  
                        "Why Mental Health is Crucial in the Workplace",  
                        "How to Plan the Perfect Road Trip",  
                        "Simple Habits for a Healthier Lifestyle",  
                        "How to Make Your Home More Eco-Friendly",  
                        "Breaking Down the Basics of Cryptocurrency",  
                        "5 Essential Skills Every Entrepreneur Needs",  
                        "How to Maximize Your Productivity in 2024",  
                        "The Benefits of Practicing Mindfulness Daily",  
                        "How to Decorate Your Home on a Budget",  
                        "Essential Tips for First-Time Homebuyers",  
                        "Top Books You Should Read This Year",  
                        "How to Overcome Self-Doubt and Build Confidence",  
                        "5 DIY Projects to Improve Your Living Space",  
                        "How to Balance Work and Family Life",  
                        "Understanding the Basics of Digital Marketing",  
                        "How to Create a Powerful Resume That Gets Noticed",  
                        "7 Ways to Manage Stress Effectively",  
                        "Why You Should Start Meditating Today",  
                        "How to Create Meaningful Connections on Social Media",  
                        "Planning the Perfect Weekend Getaway",  
                        "How to Manage Your Finances Like a Pro",  
                        "Simple Tips for a More Sustainable Lifestyle",  
                        "How to Find Your Passion and Pursue It"
                        ];


    static $Months = [
        "January",
        "Feburary",
        "March",
        "April",
        "May",
        "June",
        "July",
        "Auguse",
        "September",
        "Octover",
        "November",
        "December",
    ];



}
?>